const page = {
  title: "Default",
  published: true,
  authorId: 1,
  components: [
    {
      icon: "info",
      name: "Sobre mim",
      type: "panel",
      details:
        "Me chamo Gabriel Gaboardi, estudante de engenharia da computacao prestes a concluir o curso, fascinado em entender e analisar novas tecnologias e seus impactos num mundo de realidades que a humanidade jamais lidou antes",
    },
    {
      icon: "telegram",
      name: "Telegram",
      type: "icon",
      address: "https://web.whatsapp.com",
    },
    {
      icon: "code",
      name: "Github",
      type: "link",
      address: "https://github.com/gbgabo",
    },
    {
      icon: "link",
      name: "Linkedin",
      type: "link",
      address: "https://github.com/gbgabo",
    },
    {
      icon: "code",
      name: "Some of my Projects",
      type: "section",
      address: "https://github.com/TinyToolSH",
    },
    {
      icon: "info",
      name: "Wildberries",
      type: "link",
      address: "https://github.com/TinyToolSH",
    },
    {
      icon: "info",
      name: "Linky",
      type: "link",
      address: "https://github.com/TinyToolSH",
    },
    {
      icon: "info",
      name: "Tinytools",
      type: "link",
      address: "https://github.com/TinyToolSH",
    },
  ],
  styles: {
    icon: {
      left: "5%",
      display: "flex",
      fontSize: "1rem",
      position: "absolute",
    },
    page: {
      top: "0",
      width: "100%",
      height: "100%",
      zIndex: 1,
      display: "flex",
      position: "absolute",
      alignItems: "center",
      background: "linear-gradient(var(--gradient-angle), var(--bg-colors))",
      "overflow-x": "hidden",
      "--bg-colors": ["#900048", "#240041", "#19002E"],
      flexDirection: "column",
      backgroundSize: "cover",
      justifyContent: "center",
      "--gradient-angle": "180deg",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
    },
    label: {
      margin: "12px 0",
      display: "flex",
      fontSize: "1rem",
      alignItems: "center",
      transition: "margin 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms",
      alignContent: "center",
      justifyContent: "center",
    },
    panel: {
      color: "#00ffb7",
      fontSize: "1rem",
      maxWidth: "120px",
      minWidth: "20rem",
      boxSizing: "border-box",
      background: "#000000",
      "&:last-child": { borderRadius: "var(--border-radius)" },
      borderRadius: "var(--border-radius)",
      "--border-radius": "30px",
    },
    button: {
      color: "#00ffb7",
      width: "20rem",
      border: 0,
      height: 60,
      boxShadow: "0 3px 5px 2px #000000",
      boxSizing: "border-box",
      minHeight: "60px",
      alignItems: "center",
      background: "#900048",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 700,
      borderRadius: "8px",
      textTransform: "inherit",
    },
    profile: { maxWidth: "12rem", borderRadius: "20%" },
    section: {
      color: "#ffffff",
      fontFamily: "'JetBrains Mono', monospace",
    },
    iconLink: { color: "#00ffb7" },
    outlined: {
      background: "rgb(0 255 183 / 21%)",
      borderColor: "#00ffb7",
    },
    expandedIcon: {
      right: "5%",
      display: "flex",
      fontSize: "1rem",
      position: "absolute",
      flexBasis: "flex-start",
    },
    "profile-text": {
      color: "#00ffb7",
      fontFamily: "'JetBrains Mono', monospace",
      textTransform: "lowercase",
    },
  },
};
export default page;
